### ISSUE TITLE
Failure or success if login URL endpoint uses www or  not.

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/CeJS#12]
The only thing I changed was the login's url's `www`. It could be on LinguaLibre's endpoints. But I show you the error in case it wakes up something for you. cc: @poslovitch

## URL = 'https://www.lingualibre.org/api.php';
BREAKS:

```bash
yug@yug-K401UB:~/Documents/DragonsBot$ node edit-Lingualibre-filename.js # 'https://www.lingualibre.org/api.php'
get_API_parameters: Cache wwwlingualibre: path=query+siteinfo
Code : Amh.
Base : am.
List:Amh/Unilex_common_words_1 ***************************** */
Range: [00001-00200]
List:am/Unilex_common_words_1 List:Amh/Unilex_common_words_1
Error: missingparam: The "to" parameter must be set.
    at /home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/admin.js:166:15
    at check_session_badtoken (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:189:4)
    at XMLHttp_handler (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:655:4)
    at IncomingMessage.<anonymous> (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:2242:6)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Move page: Done.
Move talkpage: Done.
wiki_API_page: Not exists: [[User talk:Dragons Bot/Stop]]
The page to stop operation is not found ([[User talk:Dragons_Bot/Stop]]). The operation will continue as usual.
get_API_parameters: Cache wwwlingualibre: path=edit
wiki_API_query: 未登錄編輯？
/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:389
				throw new Error('wiki_API_query: 未登錄編輯？');
				^

Error: wiki_API_query: 未登錄編輯？
    at wiki_API_query (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:389:11)
    at Timeout._onTimeout (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:335:5)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### URL = 'https://lingualibre.org/api.php'; 
WORKS:

```bash
yug@yug-K401UB:~/Documents/DragonsBot$ node edit-Lingualibre-filename.js # 'https://lingualibre.org/api.php'
get_API_parameters: Cache lingualibreorg: path=query+siteinfo
Code : Ava.
Base : av.
List:Ava/Unilex_common_words_1 ***************************** */
Range: [00001-00200]
List:av/Unilex_common_words_1 List:Ava/Unilex_common_words_1
Move page: Done.
Move talkpage: Done.
wiki_API_page: Not exists: [[User talk:Dragons Bot/Stop]]
The page to stop operation is not found ([[User talk:Dragons_Bot/Stop]]). The operation will continue as usual.
get_API_parameters: Cache lingualibreorg: path=edit
Edit category base: Done.
Category:Speakers_in_av Category:Speakers_in_ava
Move category: Done.
```

**Comment by kanasimi** [comment]
It seems https://www.lingualibre.org/api.php redirects to https://lingualibre.org/api.php
I need more information to debug the error. You may set `CeL.set_debug(3)` or `CeL.set_debug(6)` to show the real transfer url.
